title: PolicyEngine Developer Guide
author: PolicyEngine
logo: logo.png
execute:
  execute_notebooks: 'force'
  jupyter_execute_notebooks: 'force'
latex:
  latex_documents:
    targetname: book.tex
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
repository:
  url: https://github.com/PolicyEngine/policyengine-dev
  path_to_book: docs
  branch: master
html:
  use_issues_button: true
  use_repository_button: true
